name: opt
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - holidays=0.64
  - libcxx=19.1.7
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - ply=3.11
  - pyomo=6.8.2
  - python=3.13.1
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
